name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
  
    name: My first job
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: select xcode
      run: Sudo xcode-select -switch /Applications/Xcode_14.2.app
    - name: Build and test
      run: xcodebuild clean build test -project EssentialFeeds/EssentialFeeds.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    - name: Build and test
      run: xcodebuild clean build test -workspace EssentialFeedModule.xcworkspace -scheme "CI_IOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14" ONLY_ACTIVE_ARCH=YES



      
